-- ============================================================
-- MANTHAAN OS — BASELINE TABLES (v2 — all INTEGER → BIGINT)
-- Rajasthan Viksit 2047 · Aasvaa Innovation Labs
-- Run this entire file in Supabase SQL Editor
-- ============================================================

-- ============================================================
-- TABLE 1: baseline_rural
-- ============================================================

CREATE TABLE baseline_rural (

  -- PRIMARY KEY
  id                              BIGSERIAL PRIMARY KEY,
  loaded_at                       TIMESTAMPTZ DEFAULT NOW(),

  -- ── IDENTITY ──────────────────────────────────────────────
  district                        TEXT NOT NULL,
  block                           TEXT NOT NULL,
  gram_panchayat                  TEXT NOT NULL,
  gp_id_rajdhara                  TEXT,
  sarpanch_name                   TEXT,
  sarpanch_contact                TEXT,

  -- ── GEOGRAPHY ─────────────────────────────────────────────
  revenue_villages_count          BIGINT,
  total_area_hectare              NUMERIC,
  gp_profile                      TEXT,

  -- ── DEMOGRAPHICS ──────────────────────────────────────────
  pop_census_2011                 BIGINT,
  pop_2026_est                    BIGINT,
  male_pop_2026                   BIGINT,
  female_pop_2026                 BIGINT,
  transgender_pop_2026            BIGINT,
  children_0_6_2026               BIGINT,
  children_6_14_2026              BIGINT,
  pop_14_18_2026                  BIGINT,
  senior_citizens_2026            BIGINT,
  pwd_pop_2026                    BIGINT,
  defence_personnel_2026          BIGINT,
  total_families_2026             BIGINT,
  bpl_families_2026               BIGINT,
  nfsa_families_2026              BIGINT,
  nomadic_population_2026         BIGINT,
  pucca_houses_2026               BIGINT,
  kutcha_houses_2026              BIGINT,

  -- ── AGRICULTURE ───────────────────────────────────────────
  cultivable_land_hectare         NUMERIC,
  irrigated_area_hectare          NUMERIC,
  net_sown_area_hectare           NUMERIC,
  gross_sown_area_hectare         NUMERIC,
  total_farmers_count             BIGINT,
  small_farmers_count             BIGINT,
  medium_farmers_count            BIGINT,
  large_farmers_count             BIGINT,
  drip_sprinkler_farmers_count    BIGINT,
  drip_sprinkler_area_hectare     NUMERIC,
  agri_electricity_connections    BIGINT,
  agri_electricity_units_daily    NUMERIC,
  solar_pumps_count               BIGINT,
  diesel_pumps_count              BIGINT,
  fertilizer_seed_center_avail    TEXT,
  dist_seed_center_km             NUMERIC,
  mandi_avail                     TEXT,
  mandi_village_name              TEXT,
  mandi_location                  TEXT,
  dist_mandi_km                   NUMERIC,
  rabi_crop_name                  TEXT,
  rabi_crop_area_hectare          NUMERIC,
  rabi_crop_production_quintal    NUMERIC,
  kharif_crop_name                TEXT,
  kharif_crop_area_hectare        NUMERIC,
  kharif_crop_production_quintal  NUMERIC,
  zaid_crop_name                  TEXT,
  zaid_crop_area_hectare          NUMERIC,
  zaid_crop_production_quintal    NUMERIC,
  food_storage_avail              TEXT,
  food_storage_village            TEXT,
  food_storage_location           TEXT,
  food_storage_capacity_quintal   NUMERIC,
  dist_food_storage_km            NUMERIC,
  food_processing_unit_type       TEXT,
  food_processing_unit_count      BIGINT,
  food_processing_production_qtl  NUMERIC,
  food_processing_employment      BIGINT,
  custom_hiring_center_avail      TEXT,
  cooperative_farmers_count       BIGINT,
  cooperative_farmer_loan_lakhs   NUMERIC,
  cooperative_livestock_count     BIGINT,
  cooperative_livestock_loan_lkhs NUMERIC,
  kcc_holders_count               BIGINT,
  soil_health_cards_valid         BIGINT,
  soil_health_card_area_hectare   NUMERIC,
  fpo_count                       BIGINT,
  fpo_farmers_count               BIGINT,
  fpo_land_hectare                NUMERIC,
  pm_cm_kisan_beneficiaries       BIGINT,

  -- ── DAIRY & LIVESTOCK ─────────────────────────────────────
  total_livestock_count           BIGINT,
  milch_animals_count             BIGINT,
  daily_milk_prod_litres          NUMERIC,
  milk_collection_centers         BIGINT,
  milk_collection_capacity_litres NUMERIC,
  govt_vet_centers_count          BIGINT,
  mangala_insurance_beneficiaries BIGINT,
  fishery_water_sources_count     BIGINT,
  fishery_annual_prod_quintal     NUMERIC,
  poultry_farms_count             BIGINT,
  poultry_annual_bird_count       BIGINT,
  poultry_annual_egg_count        BIGINT,
  goat_farms_count                BIGINT,
  goat_annual_count               BIGINT,
  pig_farms_count                 BIGINT,
  pig_annual_count                BIGINT,
  horticulture_area_hectare       NUMERIC,
  horticulture_farmers_count      BIGINT,
  floriculture_area_hectare       NUMERIC,
  floriculture_farmers_count      BIGINT,
  organic_farming_area_hectare    NUMERIC,
  organic_farming_farmers_count   BIGINT,
  polyhouse_area_hectare          NUMERIC,
  polyhouse_farmers_count         BIGINT,
  mulching_tunnel_area_hectare    NUMERIC,
  mulching_tunnel_farmers_count   BIGINT,
  crop_insurance_area_hectare     NUMERIC,
  crop_insurance_farmers_count    BIGINT,

  -- ── HEALTH ────────────────────────────────────────────────
  allopathic_centers              BIGINT,
  ayush_centers                   BIGINT,
  private_health_centers          BIGINT,
  health_center_name              TEXT,
  health_center_location          TEXT,
  health_center_village           TEXT,
  health_center_type              TEXT,
  health_center_beds              BIGINT,
  is_ayushman_arogya_mandir       TEXT,
  sanctioned_health_staff         BIGINT,
  working_health_staff            BIGINT,
  avg_daily_patients              NUMERIC,
  phc_dist_km                     NUMERIC,
  chc_dist_km                     NUMERIC,
  diabetes_screened_fy2526        BIGINT,
  bp_screened_fy2526              BIGINT,
  endemic_disease_affected        TEXT,
  anemic_pregnant_women_count     BIGINT,
  anemic_children_count           BIGINT,
  tb_patients_count               BIGINT,
  snp_children_6_72m              BIGINT,
  ayushman_arogya_beneficiaries   BIGINT,
  janaadhar_registered_families_pct NUMERIC,
  biomedical_waste_facility       TEXT,
  annapurna_rasoi_operational     TEXT,
  annapurna_daily_beneficiaries   BIGINT,

  -- ── ANGANWADI / ICDS ──────────────────────────────────────
  anganwadi_centers_count         BIGINT,
  anganwadi_center_code           TEXT,
  anganwadi_center_type           TEXT,
  anganwadi_location              TEXT,
  anganwadi_village               TEXT,
  anganwadi_electricity           TEXT,
  anganwadi_water                 TEXT,
  anganwadi_toilet                TEXT,
  anganwadi_govt_building         TEXT,
  anganwadi_workers_count         BIGINT,
  anganwadi_helpers_count         BIGINT,
  asha_workers_count              BIGINT,
  anganwadi_enrolled_children     BIGINT,
  growth_monitoring_children      BIGINT,
  preschool_monitoring_children   BIGINT,
  anganwadi_pregnant_women        BIGINT,
  sam_children_count              BIGINT,

  -- ── EDUCATION ─────────────────────────────────────────────
  govt_schools_count              BIGINT,
  school_type                     TEXT,
  school_name                     TEXT,
  school_location                 TEXT,
  school_village                  TEXT,
  total_enrolled_students         BIGINT,
  useful_classrooms_count         BIGINT,
  school_drinking_water           TEXT,
  school_playground               TEXT,
  school_toilet_avail             TEXT,
  school_girls_toilet_avail       TEXT,
  sanctioned_teachers             BIGINT,
  working_teachers                BIGINT,
  computers_for_education         BIGINT,
  smart_class_avail               TEXT,
  students_class_0_5_boys         BIGINT,
  students_class_0_5_girls        BIGINT,
  students_class_6_8_boys         BIGINT,
  students_class_6_8_girls        BIGINT,
  students_class_9_10_boys        BIGINT,
  students_class_9_10_girls       BIGINT,
  students_class_11_12_boys       BIGINT,
  students_class_11_12_girls      BIGINT,
  students_above_class_12_boys    BIGINT,
  students_above_class_12_girls   BIGINT,
  pvt_schools_count               BIGINT,
  pvt_school_type                 TEXT,
  pvt_school_enrolled_students    BIGINT,
  total_schools_count             BIGINT,
  dropout_children_prev_year      BIGINT,
  dropout_main_reason             TEXT,
  skill_training_centers_count    BIGINT,
  skill_trained_students_annual   BIGINT,
  higher_edu_institutions_count   BIGINT,
  college_enrolled_students       BIGINT,
  govt_hostels_count              BIGINT,
  govt_hostel_students            BIGINT,

  -- ── SOCIAL WELFARE ────────────────────────────────────────
  old_age_pensioners              BIGINT,
  widow_pensioners                BIGINT,
  pwd_pensioners_est              BIGINT,
  pm_ujjwala_beneficiaries        BIGINT,
  pm_cm_awas_beneficiaries        BIGINT,

  -- ── ECONOMY / LIVELIHOODS ─────────────────────────────────
  lakhpati_didis_count            BIGINT,
  millionaire_didis_count         BIGINT,
  large_industrial_units          BIGINT,
  large_industry_employment       BIGINT,
  active_shg_count                BIGINT,
  women_in_shgs                   BIGINT,
  shg_with_bank_account           BIGINT,
  shg_first_tranche_received      BIGINT,
  shg_fund_amount_lakhs           NUMERIC,
  shg_bank_linkage_count          BIGINT,
  shg_livelihood_types            TEXT,
  local_artisans_count            BIGINT,
  artisan_livelihood_types        TEXT,
  total_employed_persons          BIGINT,
  small_scale_industries          BIGINT,
  small_scale_industry_types      TEXT,
  small_scale_industry_employment BIGINT,
  mudra_loan_beneficiaries        BIGINT,
  mining_stonework                TEXT,
  main_mineral_type               TEXT,

  -- ── INFRASTRUCTURE ────────────────────────────────────────
  main_road_type                  TEXT,
  road_length_km                  NUMERIC,
  houses_with_electricity         BIGINT,
  gss_count                       BIGINT,
  solar_installed_houses          BIGINT,
  avg_electricity_hours_daily     NUMERIC,
  panchayat_bhawan_count          BIGINT,
  total_public_buildings          BIGINT,
  public_toilets                  BIGINT,
  solar_public_buildings          BIGINT,
  rainwater_harvest_public_bldgs  BIGINT,
  dist_main_market_km             NUMERIC,
  govt_banks_count                BIGINT,
  pvt_banks_count                 BIGINT,
  cooperative_banks_count         BIGINT,
  post_offices_count              BIGINT,
  pm_jan_dhan_accounts            BIGINT,
  dist_bank_km                    NUMERIC,
  total_street_lights             BIGINT,
  solar_street_lights             BIGINT,
  accessible_public_buildings     BIGINT,
  sports_grounds_count            BIGINT,
  public_transport_avail          TEXT,
  dist_bus_stand_km               NUMERIC,
  dist_railway_station_km         NUMERIC,
  broadband_avail                 TEXT,
  internet_avail                  TEXT,

  -- ── WATER & SANITATION ────────────────────────────────────
  drinking_water_sources_count    BIGINT,
  water_demand_daily_litres       NUMERIC,
  water_supply_daily_litres       NUMERIC,
  phed_non_tubwell_supply_litres  NUMERIC,
  phed_non_tubwell_houses         BIGINT,
  phed_tubwell_supply_litres      NUMERIC,
  handpump_tubewell_only_houses   BIGINT,
  overhead_tanks_count            BIGINT,
  overhead_tank_supply_litres     NUMERIC,
  tanker_supply_litres            NUMERIC,
  tanker_only_supply_houses       BIGINT,
  tap_connection_pct              NUMERIC,
  agri_water_supply_sources       TEXT,
  public_water_facilities_count   BIGINT,
  ro_facilities                   BIGINT,
  water_quality_issues_reported   TEXT,
  water_quality_test_frequency    BIGINT,
  groundwater_depth_meters        NUMERIC,
  groundwater_recharge_structures BIGINT,
  houses_with_toilets             BIGINT,

  -- ── ENVIRONMENT ───────────────────────────────────────────
  vacant_land_for_plantation_ha   NUMERIC,
  govt_nurseries_count            BIGINT,
  nursery_plants_count            BIGINT,
  pasture_land_hectare            NUMERIC,
  forest_area_hectare             NUMERIC,
  public_bldg_plantation_land_ha  NUMERIC,
  pm_surya_ghar_solar_houses      BIGINT,
  domestic_wastewater_daily_ltr   NUMERIC,
  decentralised_ww_mgmt_houses    BIGINT,
  community_ww_mgmt_houses        BIGINT,
  sewerage_network_avail          TEXT,
  total_waste_daily_kg            NUMERIC,
  dry_waste_daily_kg              NUMERIC,
  wet_waste_daily_kg              NUMERIC,
  mrf_rrc_sheds_count             BIGINT,
  waste_dump_sites_count          BIGINT,
  waste_collection_system_type    TEXT,
  door_to_door_collection_houses  BIGINT,
  two_bin_segregation_applied     TEXT,
  govt_compost_pits_count         BIGINT,
  govt_compost_pits_capacity_kg   NUMERIC,
  pvt_compost_pits_count          BIGINT,
  pvt_compost_pits_capacity_kg    NUMERIC,
  biogas_plants_count             BIGINT,
  biogas_plants_capacity_kg       NUMERIC,
  other_waste_processing_units    BIGINT,

  -- ── TOURISM & CULTURE ─────────────────────────────────────
  major_fairs_festival_names      TEXT,
  annual_fairs_count              BIGINT,
  avg_fair_footfall_daily         NUMERIC,
  fair_stalls_count               BIGINT,
  fair_product_stalls_count       BIGINT,
  fair_shg_stalls_count           BIGINT,
  avg_stall_daily_revenue_rs      NUMERIC,
  cultural_assets_count           BIGINT,
  avg_daily_footfall_cultural_sites NUMERIC,
  fair_basic_facilities           TEXT,
  fair_road_access                TEXT,
  fair_water_daily_litres         NUMERIC,
  fair_related_employment         BIGINT,
  fair_public_toilet_avail        TEXT,
  registered_trained_guides       BIGINT,

  -- ── GOVERNANCE ────────────────────────────────────────────
  emitra_avail                    TEXT,
  dist_emitra_km                  NUMERIC,
  dist_police_station_km          NUMERIC,
  dist_lpg_distributor_km         NUMERIC,
  dist_fire_station_km            NUMERIC

);

-- Performance indexes only (no unique constraint — data has duplicate GPs)
CREATE INDEX IF NOT EXISTS idx_baseline_rural_district ON baseline_rural (district);
CREATE INDEX IF NOT EXISTS idx_baseline_rural_block    ON baseline_rural (district, block);

COMMENT ON TABLE baseline_rural IS 'Rural GP-level baseline data — Rajasthan Viksit 2047. All integer columns use BIGINT. Truncate-and-reload on update.';


-- ============================================================
-- TABLE 2: baseline_urban
-- ============================================================

CREATE TABLE baseline_urban (

  -- PRIMARY KEY
  id                              BIGSERIAL PRIMARY KEY,
  loaded_at                       TIMESTAMPTZ DEFAULT NOW(),

  -- ── IDENTITY ──────────────────────────────────────────────
  district                        TEXT NOT NULL,
  ulb                             TEXT NOT NULL,
  ward                            TEXT NOT NULL,
  ward_id_rajdhara                TEXT,
  ward_incharge_name              TEXT,
  ward_incharge_contact           TEXT,

  -- ── GEOGRAPHY ─────────────────────────────────────────────
  total_area_hectare              NUMERIC,
  urban_profile                   TEXT,

  -- ── DEMOGRAPHICS ──────────────────────────────────────────
  pop_census_2011                 BIGINT,
  pop_2026_est                    BIGINT,
  male_pop_2026                   BIGINT,
  female_pop_2026                 BIGINT,
  transgender_pop_2026            BIGINT,
  children_0_6_2026               BIGINT,
  children_6_14_2026              BIGINT,
  pop_14_18_2026                  BIGINT,
  senior_citizens_2026            BIGINT,
  pwd_pop_2026                    BIGINT,
  defence_personnel_2026          BIGINT,
  pucca_houses_2026               BIGINT,
  kutcha_houses_2026              BIGINT,

  -- ── HEALTH ────────────────────────────────────────────────
  allopathic_centers              BIGINT,
  ayush_centers                   BIGINT,
  private_health_centers          BIGINT,
  health_center_name              TEXT,
  health_center_type              TEXT,
  health_center_location          TEXT,
  health_center_beds              BIGINT,
  is_ayushman_arogya_mandir       TEXT,
  sanctioned_health_staff         BIGINT,
  working_health_staff            BIGINT,
  avg_daily_patients              NUMERIC,
  snp_children_6_72m              BIGINT,
  diabetes_screened_fy2526        BIGINT,
  bp_screened_fy2526              BIGINT,
  endemic_disease_affected        TEXT,
  tb_patients_count               BIGINT,
  anemic_pregnant_women_count     BIGINT,
  anemic_children_count           BIGINT,
  ayushman_arogya_beneficiaries   BIGINT,
  janaadhar_reg_families_pct      NUMERIC,
  biomedical_waste_facility       TEXT,
  annapurna_rasoi_operational     TEXT,
  annapurna_daily_beneficiaries   BIGINT,

  -- ── ANGANWADI / ICDS ──────────────────────────────────────
  anganwadi_centers_count         BIGINT,
  anganwadi_center_code           TEXT,
  anganwadi_center_type           TEXT,
  anganwadi_location              TEXT,
  anganwadi_workers_count         BIGINT,
  anganwadi_helpers_count         BIGINT,
  asha_workers_count              BIGINT,
  anganwadi_enrolled_children     BIGINT,
  preschool_monitoring_children   BIGINT,
  growth_monitoring_children      BIGINT,
  sam_children_count              BIGINT,
  anganwadi_pregnant_women        BIGINT,
  anganwadi_electricity           TEXT,
  anganwadi_water                 TEXT,
  anganwadi_toilet                TEXT,
  anganwadi_govt_building         TEXT,

  -- ── EDUCATION ─────────────────────────────────────────────
  govt_schools_count              BIGINT,
  school_name                     TEXT,
  school_location                 TEXT,
  school_type                     TEXT,
  total_enrolled_students         BIGINT,
  useful_classrooms_count         BIGINT,
  school_drinking_water           TEXT,
  school_playground               TEXT,
  school_toilet_avail             TEXT,
  school_girls_toilet_avail       TEXT,
  sanctioned_teachers             BIGINT,
  working_teachers                BIGINT,
  computers_for_education         BIGINT,
  smart_class_avail               TEXT,
  pvt_schools_count               BIGINT,
  pvt_school_type                 TEXT,
  pvt_school_enrolled_students    BIGINT,
  total_schools_count             BIGINT,
  dropout_children_prev_year      BIGINT,
  dropout_main_reason             TEXT,
  students_class_0_5_boys         BIGINT,
  students_class_0_5_girls        BIGINT,
  students_class_6_8_boys         BIGINT,
  students_class_6_8_girls        BIGINT,
  students_class_9_10_boys        BIGINT,
  students_class_9_10_girls       BIGINT,
  students_class_11_12_boys       BIGINT,
  students_class_11_12_girls      BIGINT,
  students_above_class_12_boys    BIGINT,
  students_above_class_12_girls   BIGINT,
  higher_edu_institutions_count   BIGINT,
  college_enrolled_students       BIGINT,
  govt_hostels_count              BIGINT,
  govt_hostel_students            BIGINT,
  skill_training_centers_count    BIGINT,
  skill_trained_persons_count     BIGINT,

  -- ── SOCIAL WELFARE ────────────────────────────────────────
  old_age_pensioners              BIGINT,
  widow_pensioners                BIGINT,
  pwd_pensioners_est              BIGINT,
  pm_ujjwala_beneficiaries        BIGINT,
  pm_cm_awas_beneficiaries        BIGINT,

  -- ── ECONOMY / LIVELIHOODS ─────────────────────────────────
  large_industrial_units          BIGINT,
  large_industry_employment       BIGINT,
  small_scale_industries          BIGINT,
  small_scale_industry_employment BIGINT,
  active_shg_count                BIGINT,
  women_in_shgs                   BIGINT,
  shg_with_bank_account           BIGINT,
  shg_fund_amount_lakhs           NUMERIC,
  shg_bank_linkage_count          BIGINT,
  shg_livelihood_types            TEXT,
  local_artisans_count            BIGINT,
  artisan_livelihood_types        TEXT,

  -- ── INFRASTRUCTURE ────────────────────────────────────────
  main_road_type                  TEXT,
  road_length_km                  NUMERIC,
  houses_with_electricity         BIGINT,
  gss_count                       BIGINT,
  solar_installed_houses          BIGINT,
  avg_electricity_hours_daily     NUMERIC,
  community_buildings_count       BIGINT,
  public_toilets                  BIGINT,
  solar_public_buildings          BIGINT,
  rainwater_harvest_public_bldgs  BIGINT,
  sports_grounds_count            BIGINT,
  dist_main_market_km             NUMERIC,
  public_transport_avail          TEXT,
  dist_bus_stand_km               NUMERIC,
  dist_railway_station_km         NUMERIC,
  ev_charging_station_avail       TEXT,
  broadband_avail                 TEXT,
  govt_banks_count                BIGINT,
  pvt_banks_count                 BIGINT,

  -- ── WATER & SANITATION ────────────────────────────────────
  well_count                      BIGINT,
  well_supply_daily_litres        NUMERIC,
  handpump_count                  BIGINT,
  handpump_supply_daily_litres    NUMERIC,
  tank_count                      BIGINT,
  tank_supply_daily_litres        NUMERIC,
  overhead_tanks_count            BIGINT,
  overhead_tank_supply_litres     NUMERIC,
  tap_connection_pct              NUMERIC,
  ro_facilities                   BIGINT,
  water_quality_issues_reported   TEXT,
  water_quality_test_frequency    BIGINT,
  groundwater_depth_meters        NUMERIC,
  groundwater_recharge_structures BIGINT,
  houses_without_toilets          BIGINT,
  houses_without_sewerage         BIGINT,
  sanitation_workers_count        BIGINT,

  -- ── ENVIRONMENT ───────────────────────────────────────────
  vacant_land_for_plantation_ha   NUMERIC,
  govt_nurseries_count            BIGINT,
  nursery_plants_count            BIGINT,
  forest_area_hectare             NUMERIC,
  public_bldg_plantation_land_ha  NUMERIC,
  pm_surya_ghar_solar_houses      BIGINT,
  domestic_wastewater_daily_ltr   NUMERIC,
  decentralised_ww_mgmt_houses    BIGINT,
  community_ww_mgmt_houses        BIGINT,
  sewerage_network_avail          TEXT,
  waste_collection_system_type    TEXT,
  door_to_door_collection_houses  BIGINT,
  two_bin_segregation_applied     TEXT,
  govt_compost_pits_count         BIGINT,
  govt_compost_pits_capacity_kg   NUMERIC,
  pvt_compost_pits_count          BIGINT,
  pvt_compost_pits_capacity_kg    NUMERIC,

  -- ── TOURISM & CULTURE ─────────────────────────────────────
  major_fairs_festival_names      TEXT,
  annual_fairs_count              BIGINT,
  avg_fair_footfall_daily         NUMERIC,
  fair_stalls_count               BIGINT,
  fair_product_stalls_count       BIGINT,
  fair_shg_stalls_count           BIGINT,
  avg_stall_daily_revenue_rs      NUMERIC,
  fair_basic_facilities           TEXT,
  fair_road_access                TEXT,
  fair_water_daily_litres         NUMERIC,
  fair_related_employment         BIGINT,
  fair_public_toilet_avail        TEXT,
  registered_trained_guides       BIGINT,

  -- ── GOVERNANCE ────────────────────────────────────────────
  dist_police_station_km          NUMERIC,
  emitra_avail                    TEXT,
  dist_emitra_km                  NUMERIC,
  dist_lpg_distributor_km         NUMERIC,
  dist_fire_station_km            NUMERIC

);

-- Performance indexes only (no unique constraint — truncate-and-reload strategy)
CREATE INDEX IF NOT EXISTS idx_baseline_urban_district ON baseline_urban (district);
CREATE INDEX IF NOT EXISTS idx_baseline_urban_ulb      ON baseline_urban (district, ulb);

COMMENT ON TABLE baseline_urban IS 'Urban Ward-level baseline data — Rajasthan Viksit 2047. All integer columns use BIGINT. Truncate-and-reload on update.';